import { Button } from "std-widgets.slint";
export component SideBar inherits Rectangle {


    VerticalLayout {

        alignment: start;

        Button {
            text: "Rate the Day";
        }
        Button {
            text: "Health Tracker";
        }
        Button {
            text: "Dream Log";
        }
        Button {
            text: "Weather Tracker";
        }
        Button {
            text: "Spend Tracker";
        }
        Button {
            text: "Step Tracker";
        }
        Button {
            text: "Habit Tracker";
        }
        Button {
            text: "Step Tracker";
        }
        Button {
            text: "Goals for the Month";
        }
        Button {
            text: "Inspirations this Month";
        }
        Button {
            text: "Sleep Tracker";
        }
        Button {
            text: "Journal";
        }
        Image {
            source: @image-url("../assets/icons/settings-icon.svg");
        }
    }
}