import { Button, VerticalBox, TabWidget, HorizontalBox } from "std-widgets.slint";
import { YearInPixelsView } from "views/YearInPixelsView.slint";
import { SideBar } from "components/SideBar.slint";
import { MainTheme } from "styles/MainTheme.slint";

export component AppWindow inherits Window {
    preferred-height: 700px;
    preferred-width: 700px;
    background: @linear-gradient(-45deg, MainTheme.primary-black 0%, MainTheme.secondary-black 100%);


    HorizontalBox {
        padding: 0;

        navigation := SideBar {
            height: 100%;
            width: 20%;
            background: MainTheme.secondary-black;
            drop-shadow-blur: 15px;
            drop-shadow-color: MainTheme.accent;
        }

        content := Rectangle {}
    }

}

