import { Button, VerticalBox, TabWidget } from "std-widgets.slint";
import { YearInPixelsView } from "views/YearInPixelsView.slint";

export component AppWindow inherits Window {
    preferred-height: 500px;
    preferred-width: 500px;
    TabWidget {
        Tab {
            title: "Pixels";
            YearInPixelsView {}
        }
        Tab {
            title: "Weather";
        }
    }
}

